### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by demi-zz** [stas/eduroam-db#3]
The format of the date in the xml's ralm_usage and institution_usage should be year-month-day, not the current "time-setting"-like format that is used.

**Comment by stas** [comment]
Fixed the <ts> vs. <date> issue. (closed by eaf447c4a18aea6ee928b6fe108bd193ff0edab7)

**Comment by stas** [comment]
Should be fixed in 232e8870dcca4a8b753456388b630d12169d4d92
